"""Change Manufactures Collumn Name to Maker

Revision ID: 0bc5ac6f2e0d
Revises: bf917bf60f7b
Create Date: 2024-07-21 00:49:46.542968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bc5ac6f2e0d'
down_revision = 'bf917bf60f7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('makers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('consoles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('makers', sa.Integer(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'makers', ['makers'], ['id'])
        batch_op.drop_column('manufacturer')
    op.drop_table('manufacturers')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consoles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manufacturer', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'manufacturers', ['manufacturer'], ['id'])
        batch_op.drop_column('makers')

    op.create_table('manufacturers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('makers')
    # ### end Alembic commands ###
